name: setAway

on:
  schedule:
    - cron: "0 9 * * 1-5"

env:
  SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}

jobs:
  setAway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/node-setup
    - run: yarn start:setAway
